project_id = "wrbinsculqkxpusuxpis"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-contact-confirmation]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false