// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrbinsculqkxpusuxpis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyYmluc2N1bHFreHB1c3V4cGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Nzc4NTAsImV4cCI6MjA3NDM1Mzg1MH0.zBiCz-cC8UwdcJsc57lVb7RckxaMhxgAkAY_ute8hoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});